title = "Parameters for Simedis"

[Constants]
nrruns = 1
numberofVictims = 8 #per threat
creator = true
writeSimScore = false
tabularIP = false
logg = true
walkSpeed = 1.3 #m/s
quadrant = 31
offroad = true
stochasTimes = true # true false
keepAllInfo = true
inputDBname = "inputDB.sqlite"
nrBoats = 0
BoatCapacity = 0
nrAmbuPreliminary = 0 #smallNoria mil
nrFF = 0
minNurseFMP = 3
minDoctorFMP = 2
nrTriageMMT = 2
setupFMPtime = 0.0 #hospital exists
LoadFMP = 1.43
UnloadFMP = 1.43
DriveTimeFMP = 5
UnloadHosp = 1.43 #2 # may be different from UnloadFMP
HospDropOff = 4.0 #(time out ambulance)
TriageTimeT3 = 0.08
PreTriageTime = 0.5
TriageTimeUrgentDefault = 2.5
sigmaLN = 0.5 # determines shape of LogNormal function
sigmaN = 3 # Number of sigma equal to boundary -> 3 means boundary is at 3 sigma
TreatTimeDist = "Triangular"
TreatTimeBound = 0.2 # Allowed deviation from expected value (to below), expressed as a fraction
TravTimeDist = "LogNormal"
TravTimeBound = 0.25 # Allowed deviation from expected value (to below), expressed as a fraction
RescueTimeDist = "Normal"
RescueTimeBound = 0.25 # Allowed deviation from expected value (to below), expressed as a fraction
OtherTimeDist = "Normal"
OtherTimeBound = 0.2 # Allowed deviation from expected value (to below), expressed as a fraction
disrobetimes =[2.0,1.0]
passtimes =[1.0,0.33]
decontimes =[2.33,0.75]
rerobetimes =[2.4,1.2]
amst_arrivaltime = 20.0
ambushRate = 0.3



[Parameterset]
policyList =["StayPlay"] # ["ScoopRun","StayPlay"]
tourniquetList = [true] # [true,false]
pretriageList = [true] # [true,false]
supervisionList = ["Low"] # "Low", "Medium", "Normal", "High", "Flex"
hospitaldistrList = ["CloseFirst"] # ["SpreadOut", "CloseFirst"]
hospitalcapalist = ["Low"] # ["Low", "Medium", "High"]
mascalList =[false]
nrAmbuList = [8]
buildFMP=false
Policy = ""
PreTriage = true
PreTriageLocation = "ccp"
TriageLevel = "Nato" #["NATO", "None"]
hospitalOrder = []
supervisionlevels = []
TranspsupervisionLevel = ""
HospitalDistribution= ""
HospitalCapacity = ""
nrAmbuFW = 8
nrAmbuTAC = 0
Tourniquet = true
mascal = false
seed = 1