[Constants]
nrruns = 1
numberofVictims = 8
creator = false
writeSimScore = false
tabularIP = false
logg = true
walkSpeed = 1.3
quadrant = 31
offroad = true
stochasTimes = true
keepAllInfo = true
inputDBname = "InputDB.sqlite"
nrBoats = 0
BoatCapacity = 0
nrAmbuPreliminary = 0
nrFF = 0
minNurseFMP = 3
minDoctorFMP = 2
nrTriageMMT = 2
setupFMPtime = 0
LoadFMP = 1.43
UnloadFMP = 1.43
DriveTimeFMP = 5
UnloadHosp = 1.43
HospDropOff = 4
TriageTimeT3 = 0.08
PreTriageTime = 0.5
TriageTimeUrgentDefault = 2.5
sigmaLN = 0.5
sigmaN = 3
TreatTimeDist = "Triangular"
TreatTimeBound = 0.2
TravTimeDist = "LogNormal"
TravTimeBound = 0.25
RescueTimeDist = "Normal"
RescueTimeBound = 0.25
OtherTimeDist = "Normal"
OtherTimeBound = 0.2
disrobetimes = [2.0,1.0]
passtimes = [1.0,0.33]
decontimes = [2.33,0.75]
rerobetimes = [2.4,1.2]
amst_arrivaltime = 20
ambushRate = 0.3

[Parameterset]
policyList = ["StayPlay","ScoopRun"]
tourniquetList = [true]
pretriageList = [true]
supervisionList = ["Low"]
hospitaldistrList = ["CloseFirst"]
hospitalcapalist = ["Low"]
mascalList = [false]
nrAmbuList = [8]
buildFMP = false
Policy = ""
PreTriage = true
PreTriageLocation = "ccp"
TriageLevel = "Nato"
hospitalOrder = []
supervisionlevels = []
TranspsupervisionLevel = ""
HospitalDistribution = ""
HospitalCapacity = ""
nrAmbuFW = 8
nrAmbuTAC = 0
Tourniquet = true
mascal = false
seed = 1
